version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
      - "./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/etc/ssl:/etc/ssl"
      - "./:/var/www/html"
      - "./docker/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "443:443"
    environment:
      - NGINX_HOST=localhost
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - composer
      - mysqldb
  php:
    image: nanoninja/php-fpm:latest
    restart: always
    environment:
      - DEBUG_MODE=true
    volumes:
      - "./docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"
  mysqldb:
    image: mariadb:10.5.8
    container_name: mariadb
    restart: always

    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "8989:3306"
    volumes:
      - "./docker/data/db/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  composer:
    image: composer:2.0.8
    command: install
    working_dir: /var/www/html
    volumes:
      - "./:/var/www/html"
    depends_on:
      - php
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: app/app
    volumes:
      - "./:/var/www/html"
    ports:
      - "3000:3000"
